DROP TABLE IF EXISTS library;
CREATE TABLE library (
    library_id VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NULL DEFAULT NULL,
    url VARCHAR(255) NULL DEFAULT NULL,
    library_type VARCHAR(255) NOT NULL DEFAULT '',
    country VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS volumetry;
CREATE TABLE volumetry (
    library_id VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    value INTEGER NOT NULL DEFAULT 0,
    inserted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vol_lib FOREIGN KEY (library_id) REFERENCES library(library_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS systempreference;
CREATE TABLE systempreference (
    library_id VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    value TEXT NULL,
    CONSTRAINT syspref_lib FOREIGN KEY (library_id) REFERENCES library(library_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
